-- FPFF Course Content: 3 Lessons + Quiz + 20 Questions
-- Course ID: 152  |  STCW Regulation VI/1, Section A-VI/1, Table A-VI/1-2
-- Images extracted from PAM-MAE-FPFF-13.docx â†’ publichttps://pamel.edu.pa/uploads/fpff/

UPDATE lms_courses SET
  course_code    = 'FPFF',
  title          = 'Fire Prevention and Fire Fighting',
  status         = 'published',
  category_id    = 6,
  image          = 'https://pamel.edu.pa/uploads/fpff/image1.jpeg',
  level          = 'beginner',
  pass_percentage = 70,
  description    = 'This course provides the mandatory minimum standards of competence for Fire Prevention and Fire Fighting in accordance with Regulation VI/1, Section A-VI/1 and Table A-VI/1-2 of the STCW Code. Topics include the principles of fire and explosion, properties of flammable materials, fire hazards onboard ships, firefighting organization and emergency procedures, selection and use of firefighting equipment, fire classification and extinguishing agents, and the use of breathing apparatus. The course is delivered over 17 contact hours combining theoretical instruction and practical workshops.'
WHERE id = 152;

-- Delete existing lessons (IDs 391, 392, 393 â€” old drafts)
DELETE FROM lms_lessons WHERE course_id=152;

-- Delete existing quizzes and questions
DELETE FROM lms_question_options WHERE question_id IN (
    SELECT id FROM lms_questions WHERE quiz_id IN (SELECT id FROM lms_quizzes WHERE course_id=152)
);
DELETE FROM lms_questions WHERE quiz_id IN (SELECT id FROM lms_quizzes WHERE course_id=152);
DELETE FROM lms_quizzes WHERE course_id=152;

-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
-- LESSONS (3 chapters, 17 hours total: 11 theoretical + 6 practical)
-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

INSERT INTO lms_lessons (course_id, title, content, type, order_num, duration, is_active) VALUES

(152, 'Chapter 1: Introduction, Security and Principles',
'<h2>Introduction, Security and Principles</h2>
<p>Without a doubt, one of the main causes of accidents onboard ships is fire. This is because of the presence of high temperature, the excess quantity of flammable oil and other combustible materials.</p>
<p>A ship is approved to sail in international waters only if it is constructed as per the Fire Safety System code and carries required Fire Fighting Appliances approved by the concerned authority. A ship is fitted with various types of fire retardant and firefighting equipment so as to fight any kind of fire and extinguish it as soon as possible before it turns into a major catastrophic situation.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image2.png" alt="Fire triangle and explosion triangle diagram" style="max-width:100%;border-radius:8px;margin:16px 0;">

<h3>1. Concept and Application of the Triangle of Fire and Explosion</h3>
<p>The triangle of fire and explosion has been a crucial aspect of human life since ancient times. Fire has served various purposes, including cooking food, keeping warm, and protecting against predators. However, when fire escapes control, it can lead to loss of property and life. Fire is a violent oxidation process characterized by flames, heat, and gases.</p>

<h3>1.1 Fire Conditions</h3>
<p>Fires are caused by the action of a heat source powerful enough to initiate combustion. These causes can be classified as follows:</p>
<ul>
<li><strong>Electric Causes:</strong> Short circuit, arc current, overheating.</li>
<li><strong>Friction:</strong> Heating by friction.</li>
<li><strong>Naked flames:</strong> Candles, wicks and matches in a state of ignition.</li>
<li><strong>Sparks or combustion:</strong> Sparks and embers from combustion of solids.</li>
<li><strong>Welding:</strong> When acetylene is used carelessly.</li>
</ul>
<img src="https://pamel.edu.pa/uploads/fpff/image3.jpeg" alt="Ignition sources diagram" style="max-width:100%;border-radius:8px;margin:16px 0;">
<ul>
<li><strong>Hot surfaces:</strong> Plates, motors, hot water heaters.</li>
<li><strong>Static electricity:</strong> Generated by systems involving friction.</li>
</ul>

<h3>1.2 Properties of Flammable Materials</h3>
<p>Oxidation is the process by which a substance combines with oxygen. In this process, energy is normally released. Sometimes oxidation is slow (e.g., rusting of iron); at other times it can be rapid, producing visible fire and light.</p>
<p><strong>FUELS</strong> â€” A substance capable of burning in the presence of oxygen and given sufficient activation energy.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image4.png" alt="Fuel categories and properties" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p>Fuels are classified into three categories:</p>
<ul>
<li><strong>Solid Fuels</strong></li>
<li><strong>Liquid Fuels</strong></li>
<li><strong>Gaseous Fuels</strong></li>
</ul>
<img src="https://pamel.edu.pa/uploads/fpff/image5.jpeg" alt="Types of fuel illustration" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p><strong>SOLID FUELS:</strong> Most solid fuels are cellulosic materials such as natural wood, paper, cardboard, and fibre-based composites. When the material is finely subdivided, the danger of initiation and propagation of fire increases. The burning rate of solid fuel depends on its form â€” powder or chips burn faster than blocks.</p>
<p><strong>LIQUID FUELS:</strong> Flammable liquids such as naphtha, benzene, kerosene, alcohol, and thinners are extremely hazardous. Liquid fuels release gas (vapour) at a faster rate than solid fuels due to their looser molecular structure. The vapour pressure and flashpoint determine their fire hazard level.</p>
<p><strong>GASEOUS FUELS:</strong> The most common flammable gases are hydrogen, acetylene, butane, propane, etc. All are hot to an atmosphere of oxygen and are extremely dangerous.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image6.png" alt="Gaseous fuels and combustion zones" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p><strong>COMBUSTION:</strong> A substance whose presence allows fuel to burn. In general, oxygen is considered the typical oxidizer. Others include chloric acid, ozone, and hydrogen peroxide. Fuels with a high number of carbon atoms tend to burn more readily.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image7.png" alt="Oxidation and combustion diagram" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p><strong>ENERGY ACTIVATION:</strong> This is the energy required to initiate the combustion reaction. Ignition sources providing this energy include: electrical overload or short circuit, friction between surfaces, hot surfaces, open flame, and sparks.</p>

<h4>Types and Sources of Ignition â€” Stages of Fire Development</h4>
<ul>
<li><strong>Emerging Stage:</strong> No flames, little smoke, temperature is low; large amount of combustion products is generated.</li>
<li><strong>Latent Stage:</strong> Still no significant heat or flame; begins to increase the number of smoke particles; now the fire alarm based on ion detectors can detect it.</li>
<li><strong>Stage of Call (Flames):</strong> The ignition point is reached and flames start. The amount of smoke decreases while heat increases rapidly.</li>
<li><strong>Heat Stage:</strong> A lot of heat, flames, smoke and toxic gases are generated.</li>
</ul>
<img src="https://pamel.edu.pa/uploads/fpff/image8.png" alt="Four stages of fire development: heat, flame, smoke, toxic gases" style="max-width:100%;border-radius:8px;margin:16px 0;">

<h3>1.3 Principles for Fighting Fires</h3>
<p>Various extinguishing agents are used in firefighting operations, each with a different degree of effectiveness and limitations in applicability.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image9.jpeg" alt="Fire extinguishing agents overview" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p><strong>WATER</strong> â€” The most common extinguishing agent due to its abundance. Its extinguishing action is based on cooling the burning material. Applied as a pressurized jet or fine spray over the burning surface.</p>
<ul><li>Applicable: Class A fires, some Class B fires (oil â€” applied in a specific manner).</li><li>Never use on: Class C (electrical) or Class D (metal) fires.</li></ul>
<img src="https://pamel.edu.pa/uploads/fpff/image10.png" alt="Water as extinguishing agent â€” Class A fires" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p><strong>FOAM</strong> â€” Produced by mixing aluminium sulphate with sodium bicarbonate and a stabilizer. Forms a barrier that prevents air passage and cools slightly. Used to cover the surface of burning liquids.</p>
<ul><li>Especially useful for Class B fires.</li><li>Not suitable for alcohol/acetone fires (these solvents dissolve foam).</li><li>Being electrically conductive â€” NEVER use on Class C or Class D fires.</li></ul>
<img src="https://pamel.edu.pa/uploads/fpff/image11.png" alt="Foam extinguishing agent" style="max-width:100%;border-radius:8px;margin:16px 0;">
<img src="https://pamel.edu.pa/uploads/fpff/image12.jpeg" alt="Foam application on Class B fire" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p><strong>CARBON DIOXIDE (COâ‚‚)</strong> â€” Stored under pressure in portable extinguishers and discharged through a special nozzle. Extinguishes by smothering (displacing oxygen), accompanied by slight cooling.</p>
<ul><li>Suitable for: Class B and Class C fires.</li><li>Do NOT use in confined or poorly ventilated areas (risk of asphyxia).</li></ul>
<img src="https://pamel.edu.pa/uploads/fpff/image13.png" alt="CO2 extinguisher" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p><strong>DRY CHEMICAL (Powder)</strong> â€” Mixtures of finely pulverized materials such as Sodium Carbonate, Sodium Bicarbonate, Sodium Sulphate, and Bentonite. Works by forming a layer on the burning material that starves the reaction. In portable extinguishers, the agent is ejected by a nitrogen capsule inside.</p>
<ul><li>Suitable for: Class A, B, and C fires.</li><li>NOT suitable for Class D fires.</li></ul>
<img src="https://pamel.edu.pa/uploads/fpff/image14.png" alt="Dry chemical powder extinguisher" style="max-width:100%;border-radius:8px;margin:16px 0;">

<h4>Flammable Materials Commonly Found on Board</h4>
<p>Flammable materials like rags soaked in vegetable oil or paint can cause spontaneous combustion, representing a significant fire risk onboard ships.</p>
<p><strong>ELECTRICAL EQUIPMENT AND DEFECTIVE CIRCUITS:</strong> Electrical fires are a significant cause of death and injury, often caused by faults in the electrical system. Insulated electrical cables can become brittle with age, causing shorts or sparks.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image15.jpeg" alt="Electrical cables and fire risk" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p><strong>STATIC ELECTRICITY:</strong> Static electricity accumulates on materials due to friction. When the static charge discharges, it can produce a spark sufficient to ignite flammable vapors.</p>
<p><strong>BATTERY CHARGE:</strong> Battery charges can release hydrogen â€” a highly flammable gas. Battery charging areas must be well ventilated to prevent explosive concentrations.</p>
<p><strong>LOCKERS AND STORAGE:</strong> Improper storage can lead to objects falling, mixing, or breaking electrical circuits, potentially causing fires.</p>
<p><strong>KITCHEN:</strong> The kitchen is considered a dangerous place onboard. Activities involving open flames, heat build-up of fat, and combustible materials create significant fire risk. Common hazards include stoves, electric fryers, and power sources for cooking.</p>

<h3>1.4 Fire Propagation</h3>
<p>All substances exist in one of three states: solid, liquid, or gas. In solids, molecules are tightly bonded. In liquids, molecules are attached but not as tightly. In gases, molecules move freely with weak binding forces.</p>
<p>For combustion to occur, the molecules of the substance being oxidized must be completely surrounded by oxygen molecules. Only gases can burn directly â€” solids and liquids must first be converted to vapor through heating. When a solid or liquid is heated, its molecules move faster, breaking bonds and forming a gas (vapour) that can oxidize and burn.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image16.jpeg" alt="Fire propagation and heat transfer" style="max-width:100%;border-radius:8px;margin:16px 0;">

<h3>1.5 Safety Practices</h3>
<p>A fire can be assumed to be controlled when:</p>
<ul>
<li>The extinguishing agent has been applied to the base of the fire and penetrated to the innermost part, beginning to cool it.</li>
<li>The main body of fire has been obscured â€” the fire cannot generate enough heat to re-ignite nearby fuel.</li>
<li>All possible routes of fire spread have been examined and protected.</li>
<li>A preliminary search for victims has been completed.</li>
</ul>
<p><strong>FINALIZATION OF FIRE OPERATION:</strong> Before declaring the end of a firefighting operation, the Captain must confirm the following essential points with the fire foreman:</p>
<ul>
<li>All routes of spread of fire have been examined and controlled.</li>
<li>The required level of protection has been reached and all gases and smoke are vented to the atmosphere.</li>
<li>The burned area is safe for entry without resuscitation equipment.</li>
<li>A full review of all burned materials has been completed.</li>
<li>A fire watch has been established â€” a crew member present at the scene to give notice of any resumption.</li>
<li>All firefighting equipment has been recovered, cleaned, dried, and restored to ready condition. Portable extinguishers are recharged.</li>
<li>A count of all shipboard personnel has been made to identify possible victims.</li>
</ul>
<p><strong>POST-REVIEW:</strong> After a successful firefighting operation, it is important to review the event and consider how to improve for the next time. The fire safety officer should encourage suggestions and incorporate them into the ship''s fire safety plan.</p>

<h3>1.6 Security of Continuous Surveillance</h3>
<p><strong>VIGILANT SERVICES BOARD:</strong> Surveillance is carried out by people as a detection and fire alarm system, analogous to the automatic system. The biggest difference is how it is done â€” human surveillance provides judgment and adaptability that automatic systems cannot.</p>
<p><strong>BOARD DUTIES OF WATCHMAN (FIRE PREVENTION):</strong> A watchman on board has specific duties related to detection and fire alarms. They must receive detailed instructions and comply perfectly. The fundamental duty is to transmit the alarm in case of fire â€” even without seeing the fire directly, based on smoke or odour. After transmitting the alarm, the watchman must wake passengers, use a fire extinguisher, or report to the duty officer.</p>

<h3>1.7 Patrol Systems</h3>
<p>The crew performs specific fire watch tasks. Some gang members act as researchers â€” under the protection of water from the hose, they investigate the possibility of personnel being trapped. Other crew members investigate whether fire has spread to other regions, act as messengers, or better identify the area of the fire.</p>

<h3>1.8 Fire Hazards</h3>
<p>The causes of fire are many. Among them:</p>
<p><strong>THERMAL FIRE CAUSES:</strong></p>
<ul>
<li>Overloaded electrical facilities.</li>
<li>Damage to electrical equipment.</li>
<li>Lack of control on open flames or other heat sources.</li>
<li>Placing fuel elements near sources of heat or flame.</li>
</ul>
<img src="https://pamel.edu.pa/uploads/fpff/image17.png" alt="Thermal fire causes on ships" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p><strong>HUMAN CAUSES:</strong></p>
<ul>
<li>Smoking in unauthorized places.</li>
<li>Throwing matches or cigarette butts carelessly.</li>
<li>Lack of housekeeping.</li>
</ul>
<img src="https://pamel.edu.pa/uploads/fpff/image18.jpeg" alt="Human causes of fire" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p>Flammable products should not be located near heat sources such as heaters, stoves, lighters, radiators, or sunlight. The friction of containers or other metal materials may cause sparks â€” even invisible ones. Avoid static sparking by providing proper grounding/bonding.</p>',
'text', 1, 180, 1),


(152, 'Chapter 2: Firefighting Organization',
'<h2>2. Firefighting Organization</h2>
<p>Fires on ships are the most difficult fires to control because of the wide variety of fuels on board and the many ways in which combustion products can hinder firefighting operations. Vessel design greatly complicates extinction â€” for example, when the fire is located in an apartment below deck, surrounded by steel bulkheads and decks, the fire is difficult if not impossible to reach and fight effectively.</p>

<h3>2.1 General Alarm Emergency</h3>
<p>The crew member who discovers a fire, or an indication that there is a fire, activates the alarm or reports it immediately. Delaying this can cause a small fire to become a large one â€” once fire gains intensity it spreads rapidly.</p>
<p>All fires should be reported to superiors, even those small fires that extinguish themselves. Each fire should be investigated to find out what defects or faults allowed the fire to occur, so they can be corrected and not reappear in the future.</p>

<h3>2.2 Fire Control Plans and Master List</h3>
<p>The <strong>International Convention for the Safety of Life at Sea (SOLAS)</strong> requires a mandatory document called the <strong>Table of Notes (Muster List)</strong> to be displayed on boats. It outlines the duties and responsibilities of each crew member during emergencies.</p>
<p>The table includes:</p>
<ul>
<li>Crew names and their specific duties in each emergency type.</li>
<li>A section on fire control â€” with alarm signals (sequence of bell tolls) for fire.</li>
<li>Signals for other emergencies: grounding, collision, bad weather.</li>
<li>Distribution of crew in lifeboats during vessel abandonment.</li>
</ul>
<p>It is essential for all crew members to know their specific duties in an emergency without relying on manuals.</p>

<h3>2.3 Communications</h3>
<p>Communication with the Master should be made through telephone or messenger. Communications with the fire crew must also be established and maintained. Messengers can be the most effective for this purpose â€” telephone lines can be destroyed by fire and fire crew members are constantly moving. Radio systems can also be used as an effective backup.</p>

<h3>2.4 Staff Safety Procedures</h3>
<p>SOLAS establishes the need to do periodic fire drills. These are not only an obligation under an agreement â€” they embody the principle of "better safe than sorry." An emergency may not be a common occurrence, but when it does arise, it justifies all the effort made in preparation and training. The crew must approach drills with the greatest interest and maximum application to be properly prepared for possible emergencies on board.</p>

<h3>2.5 Periodic Drills on Board</h3>
<p>It is very important to know the procedures and drills on fire prevention:</p>
<img src="https://pamel.edu.pa/uploads/fpff/image19.png" alt="Fire drill on board ship" style="max-width:100%;border-radius:8px;margin:16px 0;">
<ul>
<li>Always take into account proper protective gear and implements â€” this avoids loss of crew and accidents.</li>
<li>All equipment must be in good condition, such as spraying hoses for safety. ALL crew members must be trained to use it in case of fire.</li>
</ul>
<img src="https://pamel.edu.pa/uploads/fpff/image20.jpeg" alt="Crew fire drill training" style="max-width:100%;border-radius:8px;margin:16px 0;">
<ul>
<li>Evacuate in an orderly and quiet fashion to the lifeboats â€” the fastest way to avoid tragedy.</li>
</ul>
<img src="https://pamel.edu.pa/uploads/fpff/image21.jpeg" alt="Lifeboat evacuation drill" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p><strong>FIRE ORGANIZATION â€” Two Objectives:</strong></p>
<ol>
<li>Minimize the number of fire emergencies.</li>
<li>Quickly check that emergency consequences are minimal.</li>
</ol>
<p><strong>Time Aspect:</strong> In emergencies, actions like evacuation, extinguishing, and warning firefighters are crucial to limit consequences. The steps for effective emergency response:</p>
<ol>
<li>Detect the fire.</li>
<li>Alarm people to be evacuated.</li>
<li>Identify the escape route for evacuation.</li>
</ol>
<p>The times of detection, alarm, and evacuation are links in a chain. The network may fail at the weakest link â€” if the plan fails at any step, the entire response is compromised.</p>

<h3>2.6 Shipbuilding Provisions</h3>
<p>Shipbuilding involves a blueprint for hull, rigging, engine installations, and auxiliary services. Modern shipyards construct ships in modules. Ships are constructed with fire safety provisions including fire-resistant bulkheads, deck divisions that limit fire spread, and designated firefighting stations with ready access to equipment throughout the vessel.</p>

<h3>2.7 Emergency Fire Pump (Cargo Ships)</h3>
<p>Emergency fire pumps are crucial for cargo ships to ensure safety and prevent fires from spreading. They are independent of the main fire pump system and must be accessible even when the main machinery space is on fire or flooded. Requirements:</p>
<ul>
<li>Passenger ships: minimum two fire pumps, with the emergency pump capable of providing required flow.</li>
<li>The emergency pump must be in a safe, well-ventilated location, with isolation valves for water supply.</li>
<li>Must be capable of maintaining required pressure throughout the fire main.</li>
</ul>

<h3>2.8 Chemical Powder Applicators</h3>
<p><strong>DRY CHEMICAL:</strong> Products are mixtures of finely pulverized materials such as Sodium Carbonate, Sodium Bicarbonate, Sodium Sulphate, Sodium Silicate, and Bentonite. Works by forming a layer on the burning material, starving the chemical chain reaction.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image14.png" alt="Dry chemical powder applicator" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p>In portable extinguishers, the agent is ejected by the pressure from a nitrogen capsule located inside. Suitable for Class A, B, and C fires. NOT suitable for Class D fires.</p>

<h3>2.9 Emergency Escape Routes</h3>
<p>Emergency escape route signs and pictograms must be posted throughout the vessel conforming to IMO standards. Photo-luminescent signs facilitate location of evacuation routes, firefighting equipment, and safety areas â€” their luminance can last more than 4 hours, surpassing all standards. This is particularly important when power sources are switched off automatically during emergencies.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image22.jpeg" alt="Emergency evacuation signs on ship" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p><strong>EVACUATION SIGNS:</strong></p>
<img src="https://pamel.edu.pa/uploads/fpff/image23.png" alt="Standard IMO evacuation signs" style="max-width:100%;border-radius:8px;margin:16px 0;">
<img src="https://pamel.edu.pa/uploads/fpff/image24.jpeg" alt="Photo-luminescent escape route signs" style="max-width:100%;border-radius:8px;margin:16px 0;">

<h3>2.10 Fire Propagation â€” Sources on Board</h3>
<p><strong>ELECTRIC MOTORS:</strong> A common cause of fires on board. If not adequately maintained or working beyond their capacity or useful life, they can cause problems. Electric motors require regular inspection, testing, cleaning, and lubrication. A shorted winding or ground wire can cause the engine bearings to overheat â€” becoming an ignition source.</p>
<p><strong>ELECTRICAL EQUIPMENT:</strong> Permanently installed electrical equipment is subject to wear from saline air corrosion and vibration. This can cause sparks â€” excellent sources of ignition if flammable gases are in the vicinity. Electrical equipment installed on ships should be of special marine design, maintained properly, and used only for its intended purpose.</p>
<p><strong>LOCKERS AND DEPOSITS:</strong> Improper storage of provisions can lead to objects falling, hitting, mixing, and breaking electrical circuits â€” causing leaks and fires.</p>
<p><strong>BILGE AREAS:</strong> The lower parts of a ship''s hold where water accumulates. Fires can occur due to excessive petroleum product accumulation from piping leaks. These fires spread easily and are difficult to control â€” careful inspection of bilges is essential.</p>

<h3>2.11 Smoke and Fire Detection</h3>
<p><strong>Smoke and Fire Detection Types:</strong></p>
<ul>
<li><strong>Photoelectric Smoke Detectors:</strong> Used for small fires and organic material burning. A beam of light is emitted; when smoke passes the beam, particles scatter and refract, triggering the alarm.</li>
<li><strong>Ionization (Smoke Mechanics) Detectors:</strong> Operate by an ionization chamber using a radioactive source of Americium 241. Smoke interferes with the constant electric current created by ionization, sounding the alarm. Most common and most reliable for regular use.</li>
<li><strong>Fixed Thermo Temperature Detectors:</strong> Detect when temperature rises above a set limit due to fire. Used in areas with constant smoke presence (commercial kitchens, industrial areas).</li>
<li><strong>Flame Detectors:</strong> Infrared and Ultraviolet detectors used to detect open flames directly.</li>
<li><strong>Linear Infrared Barriers:</strong> Detect smoke in large volumes and heights over 12 meters.</li>
<li><strong>Cable Linear Temperature Detector:</strong> Sensor activated by temperature; melts when heated, producing an insulating layer and short circuit alarm.</li>
<li><strong>Manual Call Points:</strong> Mounted buttons that allow crew to manually initiate the fire alarm before the automatic detector perceives it.</li>
<li><strong>Acoustic Alarms:</strong> Warn persons within the local area of the start of a fire.</li>
</ul>
<img src="https://pamel.edu.pa/uploads/fpff/image25.jpeg" alt="Smoke and fire detection systems" style="max-width:100%;border-radius:8px;margin:16px 0;">

<h3>2.12 Automatic Fire Alarm</h3>
<p><strong>HOW TO DETECT A FIRE:</strong> Automatic fire detection can discover fire in its early stage, thereby contributing decisively to reduce damage. Different types of sensors detect incipient fire through fire phenomena such as smoke, flame, and heat.</p>
<p>It is vital to discover the fire as soon as possible â€” it is much easier to confine, control, and extinguish a fire before it has reached large proportions. A good fire detection system, well known and maintained by the crew, is the best element for fire protection on board.</p>
<p>In case of a fire, detection systems on board produce visible and audible alarms on the bridge and engine room. The officer on the bridge activates the fire crew, and the Captain investigates the cause. If a false alarm occurs, the cause must be investigated.</p>
<p><strong>AUTOMATED FIRE DETECTION SYSTEMS consist of:</strong></p>
<ul>
<li>Fire detectors and alarms.</li>
<li>Emergency power energy supply.</li>
<li>Normal source power supply.</li>
<li>Control fire detection unit.</li>
</ul>
<p><strong>DETECTORS AND FIRE ALARMS:</strong> Fire alarms detect heat, smoke, flames, or other fire indications and produce a signal. Visible alarms consist of red lights on control units. Audible alarms have bells or sirens. Modern alarm systems allow simultaneous receiving of fire alarms without interference.</p>

<h3>2.13 Classification of Fires and Appropriate Extinguishing Agents</h3>
<p>From the point of view of combustion, fires are classified into two groups:</p>
<p><strong>FLAMES:</strong> The product of a rapid and persistent chemical reaction releasing heat and light. They are visible and relate to fuels and oxidizers burning in the gas phase.</p>
<p><strong>SURFACE (GLOWING) FIRES:</strong> Combustion occurs strictly as a surface oxidation â€” no flame. Also called glowing embers or smoldering. The reaction is slow and develops from the surface toward the core of the burning material.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image26.jpeg" alt="Flames vs surface combustion" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p><strong>CLASSIFICATION AND APPLICABLE EXTINGUISHING AGENTS:</strong></p>
<img src="https://pamel.edu.pa/uploads/fpff/image9.jpeg" alt="Fire classification and extinguishing agent chart" style="max-width:100%;border-radius:8px;margin:16px 0;">

<table style="width:100%;border-collapse:collapse;margin:16px 0;">
<thead><tr style="background:#1a3a6b;color:white;">
<th style="padding:10px;text-align:left;">Class</th>
<th style="padding:10px;text-align:left;">Materials</th>
<th style="padding:10px;text-align:left;">Extinguishing Agent</th>
</tr></thead>
<tbody>
<tr style="background:#f8fafc;"><td style="padding:10px;border:1px solid #e2e8f0;"><strong>Class A</strong></td><td style="padding:10px;border:1px solid #e2e8f0;">Ordinary combustibles: wood, paper, cloth, rubber, some plastics</td><td style="padding:10px;border:1px solid #e2e8f0;">Water (cooling)</td></tr>
<tr><td style="padding:10px;border:1px solid #e2e8f0;"><strong>Class B</strong></td><td style="padding:10px;border:1px solid #e2e8f0;">Flammable liquids, fats, gases</td><td style="padding:10px;border:1px solid #e2e8f0;">Foam, COâ‚‚, dry chemical (smothering â€” exclude oxygen)</td></tr>
<tr style="background:#f8fafc;"><td style="padding:10px;border:1px solid #e2e8f0;"><strong>Class C</strong></td><td style="padding:10px;border:1px solid #e2e8f0;">Energized electrical equipment</td><td style="padding:10px;border:1px solid #e2e8f0;">COâ‚‚, dry chemical (non-conductive agents only)</td></tr>
<tr><td style="padding:10px;border:1px solid #e2e8f0;"><strong>Class D</strong></td><td style="padding:10px;border:1px solid #e2e8f0;">Combustible metals: magnesium, titanium, sodium, potassium</td><td style="padding:10px;border:1px solid #e2e8f0;">Special metal-specific agents only</td></tr>
</tbody></table>

<img src="https://pamel.edu.pa/uploads/fpff/image10.png" alt="Water extinguisher for Class A" style="max-width:100%;border-radius:8px;margin:8px 0 4px 0;">
<img src="https://pamel.edu.pa/uploads/fpff/image11.png" alt="Foam extinguisher for Class B" style="max-width:100%;border-radius:8px;margin:4px 0;">
<img src="https://pamel.edu.pa/uploads/fpff/image13.png" alt="CO2 extinguisher for Class B and C" style="max-width:100%;border-radius:8px;margin:4px 0;">
<img src="https://pamel.edu.pa/uploads/fpff/image14.png" alt="Dry chemical for Class A, B, C" style="max-width:100%;border-radius:8px;margin:4px 0 16px 0;">',
'text', 2, 180, 1),


(152, 'Chapter 3: Selection of Firefighting Devices and Equipment',
'<h2>3. Selection of Firefighting Devices and Equipment</h2>

<h3>3.1 Fire Nozzles and Hoses</h3>
<p><strong>FIRE HOSE:</strong> A firefighting hose team should consist of four members â€” at least two handling 38mm hoses and three handling 64mm hoses. The key person is the <strong>nozzle operator</strong>, who controls jet type and direction. They must have training and discipline to ensure efficient movement toward the fire and direct water to the appropriate site.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image27.png" alt="Fire hose team and nozzle types" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p><strong>FORWARD WITH HOSE â€” Procedure:</strong></p>
<ol>
<li>When a fire alarm occurs, the hose must be driven close to the fire, opening the valve mouth to the hydrant.</li>
<li>The nozzle man and support advance towards the fire.</li>
<li>The third team member holds the hose midsection.</li>
<li>The fourth team member opens the fire hydrant.</li>
<li>Once the nozzle man is in position, open water.</li>
<li>The third and fourth team members hold hoses and equipment, verifying for water spills or leaks.</li>
<li>After water arrives, the nozzle man opens slightly to release air first.</li>
<li>The hose should be closed when water starts to flow steadily.</li>
</ol>
<p>During fire drills all hoses should be deployed and installed as if fighting a real fire. The training must be as realistic as practical and possible. Groups must handle actual practice hoses leading to decks or higher, passing them through stairs and points of difficulty.</p>
<p><strong>PROPER USE OF JET:</strong> The way jets must be applied depends on the fire situation. The nozzle operator must know the type of jet to use and when to use it according to the conditions of the fire â€” solid jet, fog spray, or pattern spray.</p>

<h3>3.2 Mobile Devices</h3>
<p>Cell foam-generating equipment is especially suitable for fighting liquid fuel fires. Its use in fire protection is widely recommended wherever flammable liquids present a serious fire hazard and where a quick response is needed to extinguish.</p>
<p><strong>Frothing tank:</strong> Made of plastic resin reinforced with fibre glass (FRP). The glass fibre reinforcement provides overall chemical resistance and excellent dielectric behaviour.</p>
<p><strong>OPERATING INSTRUCTIONS:</strong></p>
<ol>
<li>Connect the water supply hose to the inlet of the dispenser.</li>
<li>Extend the hose and lance with foam.</li>
<li>Open ball valve Â½" to allow the passage of emulsifier.</li>
<li>Direct foam jet towards the base of the fire to extinguish.</li>
</ol>
<p><strong>AFTER OPERATION:</strong></p>
<ol>
<li>Disconnect the hose and wash it with clean water, removing any remaining foam, and stow.</li>
<li>Wash the dispenser and the siphon tube.</li>
<li>Refill the frothing tank to its capacity (approximately 120 litres).</li>
<li>Rinse thoroughly and stow in its housing.</li>
<li>Never leave dirty equipment after use.</li>
</ol>

<h3>3.3 Portable Fire Extinguishers</h3>
<p>There are different kinds of portable fire extinguishers found on the bulkheads of ships and walls of buildings. They are classified by capital letters (fire class) and Roman numerals indicating size (I for smallest to V for largest).</p>
<p><strong>General rules for use of portable fire extinguishers upon discovering a fire:</strong></p>
<ol>
<li>Shout "Fire!" giving meaningful data on the location of the fire.</li>
<li>Activate the nearest fire alarm.</li>
<li>Call for help in a calm, quiet, and especially clear voice.</li>
<li>If the fire is of small proportion, attempt attack with portable extinguisher â€” bearing in mind:
  <ul>
  <li>Never cross a fire to fetch a fire extinguisher if there is any suspicion of being caught by flames.</li>
  <li>Always maintain an escape route when fighting a fire with an extinguisher.</li>
  <li>If the attempt to extinguish the fire fails, immediately leave the burning compartment and close the door. Remain in place to provide information to fire personnel.</li>
  </ul>
</li>
</ol>

<h3>3.4 Firefighter Team</h3>
<p>In accordance with SOLAS 1974 (1981 Amendments), firefighter equipment must include:</p>
<p><strong>Personal protective equipment (PPE) comprising:</strong></p>
<ul>
<li>Protective clothing of material to protect skin from heat â€” waterproof outer surface.</li>
<li>Boots and rubber gloves that are not electro-conductive.</li>
<li>A rigid helmet.</li>
<li>An electric safety lamp with a minimum burning period of <strong>3 hours</strong>.</li>
</ul>
<p><strong>Respiratory system â€” one of:</strong></p>
<ul>
<li>An antismoke helmet or smoke mask with a suitable air pump and sufficient length flexible air hose.</li>
<li>A self-contained breathing apparatus (SCBA) with compressed air cylinders having capacity of minimum <strong>1,200 litres of air</strong>, or sufficient for 30 minutes of operation.</li>
</ul>
<p>Sufficient spare charges for the breathing apparatus must be kept on board.</p>
<p>Each respiratory device must keep a fireproof lifeline of sufficient length and strength to be bound by snap hook to the harness of the breathing apparatus or to a separate belt.</p>
<p><strong>ALL vessels shall carry at least two complete fireman''s outfit sets</strong>, stored ready for immediate use in easily accessible sites. If more than one set is carried, they shall be stored in widely separated positions.</p>

<h3>3.5 Fire Blankets</h3>
<p>A fire blanket is a safety device designed to extinguish small incipient fires. It consists of a sheet of flame retardant material placed over the fire to smother it by preventing the arrival of oxygen.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image28.jpeg" alt="Fire blanket use to extinguish fire" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p><strong>Types of fire blankets:</strong></p>
<ul>
<li><strong>Small (kitchen/domestic):</strong> Generally made of fibre glass, folded in a sheath or quick-release bag for fast deployment.</li>
<li><strong>Nomex blankets:</strong> Look similar to conventional blankets but are made of fire retardant fibres â€” safe for skin, eyes, and respiratory tract.</li>
</ul>
<img src="https://pamel.edu.pa/uploads/fpff/image29.jpeg" alt="Fire blanket demonstration â€” smothering a fire" style="max-width:100%;border-radius:8px;margin:16px 0;">
<ul>
<li><strong>Large (laboratory/industrial):</strong> Often made of wool (sometimes treated with liquid flame retardant). Mounted in vertical quick-release cabinets so they can be quickly removed and wrapped around a person whose clothing is on fire.</li>
<li><strong>Special welding blankets:</strong> Support up to 1600Â°C (ANSI FM-4950).</li>
</ul>

<h3>3.6 Knowledge of Fire Safety Provisions</h3>
<p>Fire safety provisions involve technical advice, campaigns, and tasks relating to fire prevention groups and organizations, ensuring the application of existing legislation in the field of fire prevention. They perform the necessary theoretical and practical training to ensure all staff are in the best conditions for performing their firefighting tasks.</p>

<h3>3.7 Fire Alarms and First Measures</h3>
<p><strong>Ionization Detectors:</strong> The most common type of smoke detector. Create a harmless level of ionizing radiation using an electrical current to create and free positively charged ions in the air. Smoke from a fire interferes with the constant electric current â€” when inhibited, the alarm sounds. May be powered by small batteries which must be periodically checked. Generally the most reliable smoke detectors, though they may not always respond to small smouldering fires.</p>
<p><strong>Photoelectric Detectors:</strong> Use light-sensitive technology to detect smoke. A beam of light is emitted in a straight line. A sensor is positioned at an angle â€” when smoke passes the light beam, light particles scatter and refract. The sensor detects the refraction and sounds an alarm. Respond better to small fires and smouldering fires than to large flames.</p>
<p><strong>Thermal (Heat) Detectors:</strong> Not a common type; do not react to smoke. Designed to respond once temperature exceeds a set limit. Not suitable for domestic use (doesn''t respond until fire has significantly raised temperature). Used in areas where smoke is constantly present â€” industrial buildings or commercial kitchens.</p>

<h3>3.8 Firefighting</h3>
<p>Fire protection encompasses all measures to protect buildings and ships from fire. Generally, three purposes are served:</p>
<ol>
<li>Saving lives.</li>
<li>Minimizing economic losses caused by fire.</li>
<li>Getting construction activities resumed in the shortest possible time.</li>
</ol>
<p><strong>Basic fire safety measures:</strong></p>
<ul>
<li><strong>Passive measures:</strong> Affecting the construction of the building/ship â€” facilitating evacuation through corridors and stairs of sufficient size, and slowing and confining the action of fire so it does not spread quickly or invade other areas.</li>
<li><strong>Active measures:</strong> Firefighting facilities and systems that actively attack or suppress fire.</li>
</ul>

<h3>3.9 Means to Fight Fires</h3>
<p>The immediate response to a fire on a ship focuses on the crew''s and officer of watch''s response. If a crew member cannot locate the fire, they should first locate it, alert the entire ship, fight the fire, and report the situation to the officer of watch.</p>
<p><strong>Locating the fire:</strong> The crew member plays a crucial role. Early detection provides crucial information about the fire''s location and nature, enabling an appropriate response. To locate a fire: touch a compartment door or bulkhead with a bare hand to check temperature. If hot, it indicates fire behind. Discolored or blistering paint, smoke passing through wiring holes, or unusual noise may also indicate fire.</p>
<p><strong>Early detection:</strong> Of prime importance. Early detection allows fire to be located, contained, and extinguished before it reaches dangerous proportions.</p>
<p><strong>Nature of the fire:</strong> The nature determines the appropriate fighting agent. Class A fires require cooling the burnt material, while Class B fires require cutting off air supply. Water is commonly used for Class A fires, while foam, COâ‚‚, and dry chemicals are used for Class B.</p>
<p><strong>Precautions when locating fire:</strong> Avoid opening compartment doors during the first response â€” this can cause a backdraft explosion. A charged hose line should be available. Crew members should not persist in searching for the fire''s location if this could endanger their life.</p>

<h3>3.10 Procedures for Fighting Fires</h3>
<p>When fire is detected on a vessel, it is important to follow protocol and respond as soon as possible. Ship fires most commonly start in the engine room â€” caused by oil leakages, boiler incidents, or electrical failures.</p>
<p><strong>Once fire is detected, several actions must be taken:</strong></p>
<ol>
<li>Sound the general alarm.</li>
<li>Inform the bridge team.</li>
<li>Assemble the fire party.</li>
<li>Isolate the fire by closing ventilation systems, skylights, doors, etc.</li>
<li>Before entering the fire space â€” crew must wear appropriate PPE and use the proper fire extinguishing system for the type of fire involved.</li>
<li>Notify all interested parties (Coast Guard, port authority, company).</li>
</ol>
<p><strong>Low Location Lighting (LLL):</strong> A fire on board can fill corridors and rooms with smoke, causing disorientation. An LLL system uses photoluminescent products to highlight rooms and corridors, directing people to safety â€” including during power failure.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image30.png" alt="Low Location Lighting system on ship" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p><strong>IMO Firefighting Signs:</strong> Specifically designed for fire emergencies, placed near firefighting equipment on board. Red firefighting signs with photo-luminescent properties correspond to IMO Res. A760(18) as amended ISO 17631:2002.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image31.png" alt="IMO firefighting signs and symbols" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p><strong>International Shore Connection:</strong> A standby hose attachment providing a connection from shore or another ship for onboard firefighting in case of total pump failure on board. Sea water is supplied at a pre-decided pressure and connected to the ship''s fire main.</p>

<h3>3.11 Small Fires â€” Class A and B</h3>
<p><strong>CLASS A FIRE:</strong> Fire involving ordinary combustible materials such as wood, cloth, paper, rubber, and some plastics. The water is used for cooling purposes â€” to reduce the temperature of the burned material below its ignition temperature.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image32.png" alt="Class A fire - wood, paper, cloth" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p><strong>CLASS B FIRE:</strong> Fires involving flammable liquids, greases, and gases. The smothering effect â€” oxygen exclusion â€” is most effective. Another method involves removing the fuel source and reducing temperature.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image33.png" alt="Class B fire - flammable liquids" style="max-width:100%;border-radius:8px;margin:16px 0;">

<h3>3.12 Consideration Fires â€” Class C and D</h3>
<p><strong>FIRE CLASS C:</strong> Fires involving energized electrical equipment. Such fires can be controlled by a non-conductive suppressant (COâ‚‚ or dry chemical). The security procedure is to try to de-energize the high voltage circuits and then treat it as a Class A or B fire, depending on the fuel involved.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image34.png" alt="Class C fire - energized electrical equipment" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p><strong>CLASS D FIRE:</strong> Fires involving combustible metals such as magnesium, titanium, zirconium, sodium, and potassium. High temperatures of some metals in combustion cause water and other common extinguishing agents to be ineffective â€” water can even cause violent reactions with some burning metals. Special extinguishing agents are required for each specific metal type and are specifically identified for that metal.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image35.png" alt="Class D fire - combustible metals" style="max-width:100%;border-radius:8px;margin:16px 0;">

<h3>3.13 General Fire Suppression Principles</h3>
<p>Fire suppression involves disrupting the essential combustion process elements: fuel, oxygen, and heat. To extinguish a fire, reduce temperature, remove fuel, or stop the chemical chain reaction:</p>
<ul>
<li><strong>Temperature reduction:</strong> Remove heat energy (water)</li>
<li><strong>Fuel removal:</strong> Cut off the fuel supply</li>
<li><strong>Oxygen dilution/exclusion:</strong> Displace or exclude oxygen (foam, COâ‚‚, nitrogen)</li>
<li><strong>Chain reaction inhibition:</strong> Interrupt the chemical chain reaction (dry chemical, Halon)</li>
</ul>

<h3>3.14 Suffocation Effect Systems: COâ‚‚ and Foam</h3>
<p><strong>FOAM</strong> is produced by mixing a solution of aluminum sulfate with sodium bicarbonate and adding a stabilizer. It removes oxygen by forming a layer that prevents air passage, and also cools somewhat. Is applied as a layer covering the surface of the burning liquid.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image11.png" alt="Foam suppression system" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p>Useful for Class B fires. Certain solvents (alcohols, acetone) dissolve foam â€” not suitable for fires of these substances. Being electrically conductive â€” never use on Class C or Class D fires.</p>
<p><strong>CARBON DIOXIDE (COâ‚‚)</strong> can be stored under pressure in portable extinguishers and discharged through a special nozzle. The extinguishing property is its smothering effect with slight cooling.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image13.png" alt="CO2 smothering effect system" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p>Do NOT use in confined or poorly ventilated areas â€” risk of asphyxia. Suitable for Class B and C fires. NOT suitable for other types.</p>

<h3>3.15 Inhibitor Effect Systems: Powders</h3>
<p><strong>DRY CHEMICAL:</strong> Mixtures of finely pulverized materials â€” Sodium Carbonate, Sodium Bicarbonate, Sodium Sulfate, Sodium Silicate, and Bentonite. Works by forming a layer on the burning material that interrupts the chemical chain reaction. In portable extinguishers, the agent is ejected by a nitrogen capsule inside.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image14.png" alt="Dry chemical inhibitor system" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p>Suitable for Class A, B, and C fires. NOT suitable for Class D fires.</p>

<h3>3.16 Cooling Effect Systems: Sprinklers and Spray Pressure</h3>
<p>Automatic sprinkler systems are one of the most reliable means to control fires. The percentage of effectiveness of sprinkler systems has been excellent for over 100 years of use. Sprinklers activate automatically when heat causes a glass bulb or fusible link to fail, releasing water directly over the fire. They provide immediate cooling and contain fire spread until firefighting teams arrive.</p>

<h3>3.17 Breathing Apparatus</h3>
<p>A breathing apparatus is a universal portable device for artificial respiration and respiratory protection. Used to facilitate breathing in smoke-filled or toxic atmospheres during firefighting and rescue operations. Requires no separate power source other than compressed air cylinders.</p>

<h3>3.18 Smoke-Free Drills</h3>
<p>The use of self-contained breathing equipment in smoke-filled exercises prepares crew for real emergency conditions.</p>
<p><strong>Support Team Tasks:</strong> The support team assists the attack team in firefighting operations by providing extra manpower, equipping them, and fetching necessary equipment and breathing apparatus. They establish a smoke-free staging area and provide supplies.</p>
<p>Additional support team responsibilities:</p>
<ul>
<li>Providing first aid to injured persons.</li>
<li>Preparing lifeboats and life rafts for evacuation.</li>
<li>Recharging self-contained breathing apparatus cylinders.</li>
<li>Conducting security patrols.</li>
<li>Providing boundary cooling.</li>
</ul>
<p>Effective communication is crucial for team success in firefighting. Team leaders receive reports, provide guidance, maintain resources, ensure proper equipment, and coordinate with the support team.</p>
<p><strong>Equipment resources for firefighting teams:</strong></p>
<ul>
<li>Self-contained breathing apparatus (SCBA).</li>
<li>Trolley sets.</li>
<li>Distress signal units.</li>
<li>Guideropes and personal guideropes.</li>
<li>Lifelines.</li>
</ul>
<p><strong>SOLAS Chapter II-2, Regulation 17 â€” Fireman''s Outfit:</strong></p>
<ul>
<li>Protective clothing protecting skin from heat radiation, burns, and scalding steam â€” outer surface water-resistant.</li>
<li>Boots and gloves of rubber or other electrically non-conducting material.</li>
<li>A rigid helmet providing effective protection against impact.</li>
<li>An electric safety lamp (hand lantern) with a minimum burning period of 3 hours.</li>
<li>An axe.</li>
</ul>

<h3>3.19 Use of Breathing Apparatus</h3>
<p>Breathing apparatus devices are used primarily in two areas: in the work of fire crews and industrial uses. For firefighting equipment, the design emphasizes strength and heat resistance. In industrial applications (mining, petrochemicals, and others), they protect workers in hazardous atmospheres.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image36.jpeg" alt="Self-contained breathing apparatus (SCBA) in use" style="max-width:100%;border-radius:8px;margin:16px 0;">
<p><strong>SCBA (Self-Contained Breathing Apparatus)</strong> â€” also known as a CABA or BA â€” is a device used in firefighting and industry to provide breathable air in hazardous environments without relying on a remote gas supply. When not used underwater, also called industrial breathing sets, air pack, or air tank.</p>
<img src="https://pamel.edu.pa/uploads/fpff/image37.png" alt="SCBA components and assembly diagram" style="max-width:100%;border-radius:8px;margin:16px 0;">

<p>Team leaders play a crucial role in directing and managing fire emergencies. They provide concise orders based on the captain''s directives and assess the situation. They must ensure team members do not take improper initiatives that could endanger their lives or worsen the fire. A report should be given for any action taken independently.</p>',
'text', 3, 540, 1);


-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
-- QUIZ
-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

INSERT INTO lms_quizzes (course_id, lesson_id, title, description, pass_percentage, time_limit, is_active)
VALUES (152, NULL,
  'Theoretical Evaluation â€” FPFF',
  'Final theoretical evaluation for Fire Prevention and Fire Fighting. Regulation VI/1, Section A-VI/1 and Table A-VI/1-2 of STCW 78 as amended. Minimum passing score: 70%.',
  70.00, 45, 1);

SET @quiz_id = LAST_INSERT_ID();

-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
-- QUESTIONS (20)
-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

INSERT INTO lms_questions (quiz_id, question, type, points, order_num) VALUES
(@quiz_id, 'What are the three essential elements of the fire triangle?', 'multiple_choice', 1, 1),
(@quiz_id, 'Which class of fire involves flammable liquids, greases and gases?', 'multiple_choice', 1, 2),
(@quiz_id, 'Which extinguishing agent should NEVER be used on Class C (electrical) fires?', 'multiple_choice', 1, 3),
(@quiz_id, 'What is the primary extinguishing action of water on a Class A fire?', 'multiple_choice', 1, 4),
(@quiz_id, 'Which type of smoke detector uses a radioactive source of Americium 241?', 'multiple_choice', 1, 5),
(@quiz_id, 'What does the acronym SCBA stand for?', 'multiple_choice', 1, 6),
(@quiz_id, 'Which fire class involves combustible metals such as magnesium and sodium?', 'multiple_choice', 1, 7),
(@quiz_id, 'COâ‚‚ extinguishers are suitable for which fire classes?', 'multiple_choice', 1, 8),
(@quiz_id, 'What is the FIRST action a crew member should take when discovering a fire?', 'multiple_choice', 1, 9),
(@quiz_id, 'What is the minimum number of complete fireman''s outfit sets required on ALL vessels per SOLAS?', 'multiple_choice', 1, 10),
(@quiz_id, 'What is the minimum burning period required for the electric safety lamp in a fireman''s outfit?', 'multiple_choice', 1, 11),
(@quiz_id, 'Why is foam NOT suitable for fires involving alcohols or acetone?', 'multiple_choice', 1, 12),
(@quiz_id, 'Where do fires on ships most commonly start?', 'multiple_choice', 1, 13),
(@quiz_id, 'What highly flammable gas is released during battery charging that creates an explosion hazard?', 'multiple_choice', 1, 14),
(@quiz_id, 'What does LLL stand for in the context of ship fire safety?', 'multiple_choice', 1, 15),
(@quiz_id, 'Which smoke detector type works by detecting light scattering caused by smoke particles?', 'multiple_choice', 1, 16),
(@quiz_id, 'What stage of fire development is characterized by flames starting, decreasing smoke, but rapidly increasing heat?', 'multiple_choice', 1, 17),
(@quiz_id, 'During firefighting operations, why should compartment doors NOT be opened immediately?', 'multiple_choice', 1, 18),
(@quiz_id, 'Dry chemical (powder) extinguishers are suitable for which fire classes?', 'multiple_choice', 1, 19),
(@quiz_id, 'What is the correct method for extinguishing a Class D (combustible metal) fire?', 'multiple_choice', 1, 20);

SET @q1  = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=1);
SET @q2  = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=2);
SET @q3  = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=3);
SET @q4  = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=4);
SET @q5  = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=5);
SET @q6  = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=6);
SET @q7  = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=7);
SET @q8  = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=8);
SET @q9  = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=9);
SET @q10 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=10);
SET @q11 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=11);
SET @q12 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=12);
SET @q13 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=13);
SET @q14 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=14);
SET @q15 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=15);
SET @q16 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=16);
SET @q17 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=17);
SET @q18 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=18);
SET @q19 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=19);
SET @q20 = (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id AND order_num=20);

INSERT INTO lms_question_options (question_id, option_text, is_correct, order_num) VALUES
-- Q1: Fuel, Oxygen, Heat
(@q1, 'Fuel, water, and heat',                                        0, 1),
(@q1, 'Fuel, oxygen, and heat',                                       1, 2),
(@q1, 'Smoke, oxygen, and heat',                                      0, 3),
(@q1, 'Fuel, nitrogen, and heat',                                     0, 4),

-- Q2: Class B
(@q2, 'Class A',                                                       0, 1),
(@q2, 'Class B',                                                       1, 2),
(@q2, 'Class C',                                                       0, 3),
(@q2, 'Class D',                                                       0, 4),

-- Q3: Foam and water (electrically conductive)
(@q3, 'COâ‚‚',                                                          0, 1),
(@q3, 'Dry chemical powder',                                           0, 2),
(@q3, 'Water and foam (electrically conductive â€” risk of electrocution)', 1, 3),
(@q3, 'Nitrogen gas',                                                  0, 4),

-- Q4: Cooling
(@q4, 'Smothering â€” excluding oxygen from the fire',                   0, 1),
(@q4, 'Cooling â€” reducing the temperature below the ignition point',   1, 2),
(@q4, 'Inhibiting â€” stopping the chemical chain reaction',             0, 3),
(@q4, 'Diluting â€” reducing the concentration of fuel vapour',         0, 4),

-- Q5: Ionization (Americium 241)
(@q5, 'Photoelectric smoke detector',                                  0, 1),
(@q5, 'Ionization smoke detector',                                     1, 2),
(@q5, 'Thermal heat detector',                                         0, 3),
(@q5, 'Flame detector (ultraviolet)',                                  0, 4),

-- Q6: Self-Contained Breathing Apparatus
(@q6, 'Safety Carbon Breathing Apparatus',                             0, 1),
(@q6, 'Standard Chemical Breathing Appliance',                        0, 2),
(@q6, 'Self-Contained Breathing Apparatus',                           1, 3),
(@q6, 'Smoke Control Breathing Assembly',                              0, 4),

-- Q7: Class D
(@q7, 'Class A',                                                       0, 1),
(@q7, 'Class B',                                                       0, 2),
(@q7, 'Class C',                                                       0, 3),
(@q7, 'Class D',                                                       1, 4),

-- Q8: Class B and C only
(@q8, 'Class A and B only',                                           0, 1),
(@q8, 'Class B and C only',                                           1, 2),
(@q8, 'Class A, B, and C',                                            0, 3),
(@q8, 'All fire classes',                                             0, 4),

-- Q9: Activate the alarm
(@q9, 'Attempt to extinguish the fire with the nearest extinguisher',  0, 1),
(@q9, 'Evacuate the ship immediately',                                 0, 2),
(@q9, 'Activate the fire alarm and notify the officer of the watch',   1, 3),
(@q9, 'Close all watertight doors and portholes',                     0, 4),

-- Q10: Two
(@q10, 'One',  0, 1),
(@q10, 'Two',  1, 2),
(@q10, 'Three',0, 3),
(@q10, 'Four', 0, 4),

-- Q11: 3 hours
(@q11, '1 hour',  0, 1),
(@q11, '2 hours', 0, 2),
(@q11, '3 hours', 1, 3),
(@q11, '4 hours', 0, 4),

-- Q12: Solvents dissolve the foam
(@q12, 'Foam is too expensive for those fires',                        0, 1),
(@q12, 'Foam does not reach high enough temperatures',                 0, 2),
(@q12, 'Alcohols and acetone dissolve the foam, making it ineffective', 1, 3),
(@q12, 'Foam reacts chemically with alcohols producing toxic gas',    0, 4),

-- Q13: Engine room
(@q13, 'Bridge',                                                       0, 1),
(@q13, 'Engine room',                                                  1, 2),
(@q13, 'Cargo hold',                                                   0, 3),
(@q13, 'Crew accommodation',                                           0, 4),

-- Q14: Hydrogen
(@q14, 'Methane',   0, 1),
(@q14, 'Propane',   0, 2),
(@q14, 'Hydrogen',  1, 3),
(@q14, 'Acetylene', 0, 4),

-- Q15: Low Location Lighting
(@q15, 'Lifesaving Launch Location',           0, 1),
(@q15, 'Low Location Lighting',                1, 2),
(@q15, 'Luminescent Life-safety Label',        0, 3),
(@q15, 'Licensed Lifeguard Level',             0, 4),

-- Q16: Photoelectric
(@q16, 'Ionization detector',                         0, 1),
(@q16, 'Thermal heat detector',                       0, 2),
(@q16, 'Photoelectric detector',                      1, 3),
(@q16, 'Carbon monoxide detector',                    0, 4),

-- Q17: Stage of Call (flames begin)
(@q17, 'Emerging stage',                                                        0, 1),
(@q17, 'Latent stage',                                                          0, 2),
(@q17, 'Stage of call â€” flames start, smoke decreases, heat increases rapidly', 1, 3),
(@q17, 'Heat stage',                                                            0, 4),

-- Q18: Risk of backdraft explosion
(@q18, 'The door might be too hot to open safely',                     0, 1),
(@q18, 'The captain has not given permission yet',                     0, 2),
(@q18, 'Opening the door can cause a backdraft â€” explosion from sudden oxygen entry', 1, 3),
(@q18, 'It could allow smoke to spread to the corridor',              0, 4),

-- Q19: Class A, B, C (NOT D)
(@q19, 'Class A fires only',                                          0, 1),
(@q19, 'Class B and C fires only',                                    0, 2),
(@q19, 'Class A, B, and C fires',                                     1, 3),
(@q19, 'All fire classes including Class D',                          0, 4),

-- Q20: Special metal-specific agents only
(@q20, 'Apply large quantities of water to cool the metal',           0, 1),
(@q20, 'Use COâ‚‚ extinguisher â€” most effective on all fires',          0, 2),
(@q20, 'Use dry chemical powder â€” most universal agent available',    0, 3),
(@q20, 'Use the specific extinguishing agent designated for that particular metal', 1, 4);

-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
-- VERIFY
-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
SELECT 'Lessons created:' AS info, COUNT(*) AS total FROM lms_lessons WHERE course_id=152;
SELECT 'Quiz created:' AS info, COUNT(*) AS total FROM lms_quizzes WHERE course_id=152;
SELECT 'Questions created:' AS info, COUNT(*) AS total FROM lms_questions WHERE quiz_id=@quiz_id;
SELECT 'Options created:' AS info, COUNT(*) AS total FROM lms_question_options WHERE question_id IN (SELECT id FROM lms_questions WHERE quiz_id=@quiz_id);
SELECT 'Images extracted to:' AS info, 'https://pamel.edu.pa/uploads/fpff/' AS path;

