-- Import Moodle courses not already in lms_courses (product_id NULL for manual linking)
INSERT IGNORE INTO lms_courses (category_id, title, slug, course_code, status, price, level, pass_percentage, created_at) VALUES
(6, 'Security Awareness Training for all Seafarers', 'security-awareness-training-for-all-seafarers', 'PAM-SATAS-10', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Passenger Ship Crowd Management Training', 'passenger-ship-crowd-management-training', 'PAM-PSCMT-06', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Passenger Ship Crisis Management and Human Behaviour Training', 'passenger-ship-crisis-management-and-human-behaviour-training', 'PAM-PSCMHB-05', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Safety Training For Personnel Providing Direct Service To Passengers In Passengers Spaces', 'safety-training-for-personnel-providing-direct-service-to-passengers-in-passenge', 'PAM-STPPPS-04', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Use of Leadership & Managerial Skillserial Skills', 'refresher-course-of-use-of-leadership-managerial-skillserial-skills', 'PAM-RLEAMSK-02', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Personal Safety and Social Responsibilities ', 'refresher-course-of-personal-safety-and-social-responsibilities', 'PAM-RPSSR-01', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Safety Training For Personnel Providing Direct Service To Passengers In Passengers Spaces', 'refresher-course-of-safety-training-for-personnel-providing-direct-service-to-pa', 'PAM-RSTPPPS-04', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Passenger Ship Crisis Management and Human Behaviour Training', 'refresher-course-of-passenger-ship-crisis-management-and-human-behaviour-trainin', 'PAM-RPSCMHB-05', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Passenger Ship Crowd Management Training', 'refresher-course-of-passenger-ship-crowd-management-training', 'PAM-RPSCMT-06', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Ship Security Officer', 'refresher-course-of-ship-security-officer', 'PAM-RSSO-07', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Security Training for Seafarers with designated Security Duties', 'refresher-course-of-security-training-for-seafarers-with-designated-security-dut', 'PAM-RSTSDSD-08', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Security Awareness Training for all Seafarers', 'refresher-course-of-security-awareness-training-for-all-seafarers', 'PAM-RSATAS-9', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Leadership and Teamwork', 'refresher-course-of-leadership-and-teamwork', 'PAM-RLTW-10', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Marine Environmental Awareness', 'refresher-course-of-marine-environmental-awareness', 'PAM-RMEA-11', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Incoterms ', 'incoterms', 'PAM-INC-01', 'draft', 0, 'beginner', 70, NOW()),
(4, 'International Logistics Management', 'international-logistics-management', 'PAM-ILM-02', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Commercial Documentation Management', 'commercial-documentation-management', 'PAM-CDM-03', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Maritime Insurance', 'maritime-insurance', 'PAM-MI-04', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Maritime Resource Management', 'maritime-resource-management', 'PAM-MRM-05', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Contenerized, Cargo Filling, Packaging, Wrapping and Labelling', 'contenerized-cargo-filling-packaging-wrapping-and-labelling', 'PAM-CCC-06', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Management of Tool Box and Safety Meeting', 'management-of-tool-box-and-safety-meeting', 'PAM-MTB-07', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Container Handling Equipment and Systems', 'container-handling-equipment-and-systems', 'PAM-CHES-08', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Container Terminal Operations', 'container-terminal-operations', 'PAM-CTO-09', 'draft', 0, 'beginner', 70, NOW()),
(4, 'The Container Terminal and the International Trade', 'the-container-terminal-and-the-international-trade', 'PAM-CTIT-10', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Safe Handling of the Dangerous Goods at Port and Warehouses', 'safe-handling-of-the-dangerous-goods-at-port-and-warehouses', 'PAM-SHDG-11', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Refresher Course of Proficiency in Crisis Management and Human Behavior Training Including Passenger Safety, Cargo Safety and Hull Integrity Training', 'refresher-course-of-proficiency-in-crisis-management-and-human-behavior-training', 'PAM-RMA-03', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Maritime Economy', 'maritime-economy', 'PAM-ME-12', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Interview Techniques and Management', 'interview-techniques-and-management', 'PAM-ITM-13', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Conflict Management Skills', 'conflict-management-skills', 'PAM-CMS-15', 'draft', 0, 'beginner', 70, NOW()),
(4, 'The Personnel Wellness in the Maritime Industry', 'the-personnel-wellness-in-the-maritime-industry', 'PAM-PWM-16', 'draft', 0, 'beginner', 70, NOW()),
(5, 'Técnicas de Gestión y Calidad en la Atención al Usuario', 't-cnicas-de-gesti-n-y-calidad-en-la-atenci-n-al-usuario', 'PAM-TGCA-46', 'draft', 0, 'beginner', 70, NOW()),
(5, 'Tutorías para Escuela Primaria Matemáticas, Español, Ciencias Naturales.', 'tutor-as-para-escuela-primaria-matem-ticas-espa-ol-ciencias-naturales', 'PAM-TUTO-45', 'draft', 0, 'beginner', 70, NOW()),
(5, '¿Cómo Crear tu Negocio 2022 en Panamá?', 'c-mo-crear-tu-negocio-2022-en-panam', 'PAM-CCN-44', 'draft', 0, 'beginner', 70, NOW()),
(5, 'Básico de Photoshop', 'b-sico-de-photoshop', 'PAM-BPT-43', 'draft', 0, 'beginner', 70, NOW()),
(5, 'Gestión, Manejo y Preparación de Documentos para Actos Públicos', 'gesti-n-manejo-y-preparaci-n-de-documentos-para-actos-p-blicos', 'PAM-PREP-42', 'draft', 0, 'beginner', 70, NOW()),
(5, 'Curso de Planillas (SIPE)', 'curso-de-planillas-sipe', 'PAM-CPS-41', 'draft', 0, 'beginner', 70, NOW()),
(7, 'Officer In Charge Of The Navigational Watch In Ships Of 500 Gross Register Tonnage Or More', 'officer-in-charge-of-the-navigational-watch-in-ships-of-500-gross-register-tonna', NULL, 'draft', 0, 'beginner', 70, NOW()),
(7, 'Chief Engineer And Second Engineer Officer In Ships Of 3,000KW Propulsion Power Or More, Or Between 750kW Up To 3,000kW Propulsion Power', 'chief-engineer-and-second-engineer-officer-in-ships-of-3-000kw-propulsion-power', NULL, 'draft', 0, 'beginner', 70, NOW()),
(7, 'Electro-Technical Officer', 'electro-technical-officer', 'Electro-Technical Officer', 'draft', 0, 'beginner', 70, NOW()),
(7, 'Master And Chief Officer In Ships Of 500 Gross Register Tonnage Or More', 'master-and-chief-officer-in-ships-of-500-gross-register-tonnage-or-more', NULL, 'draft', 0, 'beginner', 70, NOW()),
(7, 'Officer In Charge Of The Engineering Watch In Ships Of 750kW Propulsion Power Or More', 'officer-in-charge-of-the-engineering-watch-in-ships-of-750kw-propulsion-power-or', NULL, 'draft', 0, 'beginner', 70, NOW()),
(4, 'The Privacy and Data Protection in the Maritime Industry', 'the-privacy-and-data-protection-in-the-maritime-industry', 'PAMEL-PDPM-14', 'draft', 0, 'beginner', 70, NOW()),
(4, 'Marine Resources ', 'marine-resources', 'PAMEL-MARE-17', 'draft', 0, 'beginner', 70, NOW()),
(6, 'Passenger Safety, Cargo Safety and Hull Integrity Training', 'passenger-safety-cargo-safety-and-hull-integrity-training', 'PAM-PSCSH-36', 'draft', 0, 'beginner', 70, NOW()),
(6, 'ELEMENTARY FIRST AID', 'elementary-first-aid', 'PFA', 'draft', 0, 'beginner', 70, NOW())
;